:bug: building doesn't work
Fails with "error TS5055: Cannot write file '/Users/astoilkov/Repos/use-local-storage-state/dist/index.d.ts' because it would overwrite input file.".
- https://stackoverflow.com/questions/42609768/typescript-error-cannot-write-file-because-it-would-overwrite-input-file
- https://github.com/Microsoft/TypeScript/issues/16394
- https://github.com/microsoft/TypeScript/issues/27436
- https://github.com/microsoft/TypeScript/issues/14538